# stack build plan using GHC 9.8.2

resolver: nightly-2024-04-10

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
- base64-0.4.2.4            # hledger-web does not yet support base64-1
- process-1.6.19.0          # for HSEC-2024-0003
- haskeline-0.8.2.1

- vty-windows-0.2.0.2       # not yet in stackage

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

# ghc-options:
#   "$locals": -Wno-x-partial
#   "$locals": -fplugin Debug.Breakpoint

# # for precise profiling, per https://www.tweag.io/posts/2020-01-30-haskell-profiling.html:
# # apply-ghc-options: everything
# # rebuild-ghc-options: true
# # stack build --profile --ghc-options="-fno-prof-auto"

# # tell GHC to write hie files, eg for weeder. Rumoured to be slow.
# # ghc-options:
# #   "$locals": -fwrite-ide-info

# # ghc-options:
# #   "$locals": -ddump-timings
# #  "$targets": -Werror
# #  "$everything": -O2
# #  some-package: -DSOME_CPP_FLAG
